### ISSUE TITLE
Question: X of Y step indicator?

### ISSUE THREAD

**Issue by ktiedt** [adi518/vue-stepper-component#10]
Rather new to VueJS so I am posting this question while I research/experiment on my own. The gist of the matter is, our designers want to use a simple "1 of 5" indicator vs a visual setup like every wizard/stepper today uses... is that easily achieved here?

**Comment by adi518** [comment]
I think so. This component uses a `v-model`, where you apply a variable and then it gets updated each time the stepper changes step. You can then pick up the variable and compose it into an "indicator" component. Do whatever you want with it. :)

**Comment by ktiedt** [comment]
I think I talked our Design guys into modernizing their mockups to avoid this problem, but I will definitely give this a try once I get to it! (got tied up in some other work before getting back to this).

Thank you for the quick reply @adi518!

**Comment by adi518** [comment]
You can try attaching a mock up so I might understand a little better. Anyway, this component attempts to be as lean as possible, so anything additional is up to the consumer. The component has slots, so make sure you take advantage of that.
