### ISSUE TITLE
Plase correct doc for dummies

### ISSUE THREAD

**Issue by ppKrauss** [adi518/vue-stepper-component#11]
(about [this readme](https://github.com/adi518/vue-stepper-component/blob/master/docs/README.md))

The  `vue init webpack` is working in a empty directory... Bu the instruction not say if is faster or necessary to do `git clone` of vue-stepper-component before.

**Comment by ppKrauss** [comment]
Bugs. After
1. `git clone https://github.com/adi518/vue-stepper-component.git`
2. `cd vue-stepper-component` 
3. ` vue init webpack`

the last command produced this error messages:
```
✖ 2 problems (2 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-stepper-component@1.0.0 lint: `eslint --ext .js,.vue src test/unit test/e2e/specs "--fix"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-stepper-component@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-20T18_00_32_321Z-debug.log

# Project initialization finished!
# ========================

To get started:

  npm run dev
  
Documentation can be found at https://vuejs-templates.github.io/webpack
```

**Comment by adi518** [comment]
I can't see how `vue init webpack` is relevant. That's an app bootstrap command. To use this component, you have to add it to your dependencies and then consume it in one of your app components.

**Comment by ppKrauss** [comment]
Thanks @adi518 , make sense (!).  

I can't check (because now on other project), so I am closing.
