### ISSUE TITLE
How can text be added to the steps?

### ISSUE THREAD

**Issue by thiagomarini** [adi518/vue-stepper-component#19]
In the project page the steps have text (Eeny, Miny, Moe) but there's nothing on the examples on how to do it.

**Comment by jswright91** [comment]
See this closed issue: 
[#18 ](https://github.com/adi518/vue-stepper-component/issues/18)

which references the code here:
https://github.com/adi518/vue-stepper-component/blob/master/docs/src/containers/Docs.vue#L32
