### ISSUE TITLE
How do I set a step title(Eeny, miny, moe) ?

### ISSUE THREAD

**Issue by cbbrsc** [adi518/vue-stepper-component#8]
Hi,
I try to use your component But I can't find in the documentation how can I set a step title. What is the property to set title of  a step?

Thanks,
Costin

**Comment by adi518** [comment]
It's a slot, not a prop. :)

**Comment by costibob** [comment]
Hi,
Do you have a sample?
Probably is a naming convention I don't get it.
Thanks.

**Comment by adi518** [comment]
Try this:

```html
<template slot="step-1"> Eeny </template>
<template slot="step-2"> Miny </template>
<template slot="step-3"> Moe </template>
```

**Comment by theGrower** [comment]
This is a great question. I want the template to pull in another component so I've done this:

```
<template v-if="step === 1"> <MyComponent1/> </template>
<template v-if="step === 2"> <MyComponent2/> </template>
<template v-if="step === 3"> <MyComponent3/> </template>
```
How can I get the title of each component inline with the v-stepper?

**Comment by adi518** [comment]
@theGrower What do you mean "inline with the v-stepper"?

**Comment by theGrower** [comment]
@adi518 Where you have "Eeny, Miny, Moe."

**Comment by adi518** [comment]
Oh. Just like I told him. There are slots. Pass into them whatever you want.

```html
<template slot="step-1"> <MyComponent1/> </template>
<template slot="step-2"> <MyComponent2/> </template>
<template slot="step-3"> <MyComponent3/> </template>
```

**Comment by theGrower** [comment]
This does not work. Nothing assigned to the slot variable shows on the page.

**Comment by theGrower** [comment]
Plain text is all that I tried. 

I think you have a good start on a component here; however, your documentation is lacking and you have some features and kinks to work out. If you have some concrete working examples/demos to provide that would be stellar. Otherwise, I don't think I'm going to be able to use your component.

**Comment by adi518** [comment]
Yes, I'm aware of that. I have a new version on another branch, but it's not finished yet. It will be, soon.

Meanwhile, follow the example [here](https://github.com/adi518/vue-stepper-component/blob/907b23cc312795c6d9dc65b2328c41e203566e6b/docs-src/src/containers/Docs.vue#L23).

**Comment by adi518** [comment]
Oh wait a minute. You are using slots incorrectly. You must nest them under `v-stepper`, otherwise it will never work. This is about Vue, not really my component. The docs will soon be a lot clearer though.

**Comment by theGrower** [comment]
> Oh wait a minute. You are using slots incorrectly. You must nest them under `v-stepper`, otherwise it will never work. This is about Vue, not really my component. The docs will soon be a lot clearer though.

I just noticed that. Re-write gave me the text. Now the buttons aren't working. Now the buttons stopped working... I'll work on that. Thank you.
