### ISSUE TITLE
Style overrides?

### ISSUE THREAD

**Issue by theGrower** [adi518/vue-stepper-component#9]
Easy way to override styles? Simple things like the background color, visited, and so forth? ... the example you put on your demo page lets the background through well; however, on my app all the background is varying shades of gray.

**Comment by adi518** [comment]
Yea, so you can customize the stepper to a degree without overriding styles, overriding CSS is basically hacking, so instead we use "scoped-slot" approach, aka "render-prop" (as they call it in React). The stepper exposes two slots per step, `step-{n}` and `step-{n}-index`. The latter allows you to compose the step index into your own template and style. Here's an example:

```html
<v-stepper>
  <template slot="step-1-index" slot-scope="scope">
    <div class="step-index"> {{ scope.displayIndex }} </div>
  </template>
</v-stepper>
```

**Comment by theGrower** [comment]
/* go crazy */ I will. Thanks for your help.

**Comment by AlissonRS** [comment]
I tried using your template and this css:

```
.step-index {
    background-color: #009688;
    color: gray;
}
```

but this is the result:

![image](https://user-images.githubusercontent.com/4753901/55360144-f352b200-54a9-11e9-81cf-f3bffc9b9ee7.png)

I wanted to be able to change the background color and the whole circle background color. How can one achieve that?

**Comment by adi518** [comment]
It's a little hard to tell what you did. Do you have a repro?

**Comment by theGrower** [comment]
I'm on vacation, however, if you inspect the HTML of your page you can figure our the higherarchy of your CSS and set up your classes appropriately. e.g. div > stepper > step-index {} ... And so forth. Once you've figured out the higherarchy, then you can set each property to change everything; text, background, shadow, etc.
